apiVersion: v1
kind: Pod
metadata:
  name: pod-for-rs-1
  namespace: default
  labels:
    # app: pod1-app
    # env: production
    app: test
spec:
  containers:
  - name: pod-for-rs-container1-alpine
    # image: registry.cn-hangzhou.aliyuncs.com/tanjunchen/network-multitool:v1
    image: alpine:latest
    # command: ["sh", "-c"]
    command: ["sh", "-c", "echo 'Hello, Kubernetes!' && sleep 3600"]  # 确保容器持续运行
    # args: ["echo 'Hello, Kubernetes!'"]
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8081
      hostPort: 8081
      protocol: UDP
    resources:
      requests:
        cpu: 1
        memory: 134217728
      limits:
        cpu: 2
        memory: 268435456