apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default
  labels:
    app: hello-world
spec:
  containers:
  - name: pod1-container1
    image: registry.cn-hangzhou.aliyuncs.com/tanjunchen/network-multitool:v1
    command: ["sh", "-c"]
    args: ["echo 'Hello again, Kubernetes!' && sleep 3600"]
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8081
      hostPort: 8081
      protocol: UDP
    resources:
      requests:
        cpu: 1
        memory: 134217728
      limits:
        cpu: 2
        memory: 268435456