# 后续应该添加kind参数，不需要显式地进行分配
apiVersion: v1
kind: ReplicaSet
metadata:
  name: hello-world-rs
  namespace: default
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world