apiVersion: v1
kind: Service
metadata:
  name: hello-world-nodeport
  namespace: default
  labels:
    app: hello-world
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP