apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-simple-writer
  namespace: default
  labels:
    app: ubuntu-simple
    role: writer
spec:
  volumes:
  - name: shared-volume
    hostPath:
      path: /tmp/k8s-shared-volume
  containers:
  - name: ubuntu-container
    image: ubuntu:latest
    command: ["sh", "-c"]
    args: ["echo 'Hello from writer pod' >> /data/writer.txt && sleep 3600"]
    volumeMounts:
    - name: shared-volume
      mountPath: /data
    resources:
      requests:
        cpu: 0.5
        memory: 134217728
      limits:
        cpu: 1
        memory: 268435456
  - name: ubuntu-container-2
    image: ubuntu:latest
    command: ["sh", "-c"]
    args: ["echo 'Hello from writer pod 2' >> /data/writer2.txt && sleep 3600"]
    volumeMounts:
    - name: shared-volume
      mountPath: /data
    resources:
      requests:
        cpu: 0.5
        memory: 134217728
      limits:
        cpu: 1
        memory: 268435456