apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: default
  labels:
    app: hello-world
spec:
  type: ClusterIP
  cluster_ip: 0.0.0.0
  selector:
    app: hello-world
  ports:
  - name: http
    port: 80 # service在集群内部暴露的端口
    targetPort: 8080 # pod实际暴露的端口
    protocol: TCP

