apiVersion: v1
kind: DNS
metadata:
  name: dns-test
  namespace: default
spec:
  host: example.com
  paths:
    - path: /app1
      serviceName: hello-world-service
      servicePort: 80
    - path: /app2
      serviceName: app2-service
      servicePort: 80
