apiVersion: v1
kind: Pod
metadata:
  name: test-server-3
  namespace: default
  labels:
    app: hello-world
    server: "3"
spec:
  containers:
  - name: test-server-container
    image: registry.cn-hangzhou.aliyuncs.com/tanjunchen/network-multitool:v1
    command: ["sh", "-c"]
    args: ["echo 'Starting server 3 on port 9090...' && while true; do echo -e 'HTTP/1.1 200 OK\\r\\nContent-Type: text/plain\\r\\nContent-Length: 31\\r\\n\\r\\nResponse from SERVER-3 (Pod 3)' | nc -l -p 9090; done"]
    ports:
    - containerPort: 9090
      protocol: TCP
    resources:
      requests:
        cpu: 1
        memory: 134217728
      limits:
        cpu: 2
        memory: 268435456
