apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config
    namespace: default
data:
    nginx.conf: |
        events {
            worker_connections 1024;
        }
        http {
            include mime.types;
            default_type application/octet-stream;
            server {
                listen 80;
                server_name example.com;
        
                location /app1 {
                    proxy_pass http://10.96.121.175:80;
                    proxy_set_header Host $host;
                }
            }
        }