apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default
  labels:
    app: flask-server
spec:
  containers:
  - name: pod-server
    image: registry.cn-hangzhou.aliyuncs.com/nyteplus/cni-server:latest
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8081
      hostPort: 8081
      protocol: UDP